<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl= $acl_container->acl;
$role= $user_session->role;
?>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="panel panel-default">

        <div class="panel-heading">
                    <div class="row">
            <div class="col-sm-8">
                <h2>Edit A District</h2>
            </div>
            <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\District', 'index')){?>
                <div class="col-sm-4">
                    <a href="<?php echo $this->url('district', array('action' => 'index')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-list "></i>&nbsp;District list</a>

                </div>
                <?php } ; ?>
            <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

                    </div>
        </div>


    


    <div class="panel-body">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <form action="<?php $this->url('district', array('action' => 'edit','id' => $this->id)); ?>" name="form" method="post" onsubmit="return validateForm()">
                    <?php
                    $form->prepare();
                    $form->get('district_name')->setAttributes([
                        'class' => 'form-control',
                        'placeholder' => 'Name of District',
                        'autocomplete' => 'off',
                        'id' => 'District Name',
                        'onclick' => 'emptyInput(this)',
//                           
                    ]);

                     $region = [];
                        foreach ($regions as $r) {
                            $region[$r['id']] = $r['region_name'];
                        }
                        
                        $form->get('region')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Region',
                            'options' => $region,
                            'autocomplete' => 'off',
                            'id' => 'Region',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                    $form->get('submit')->setAttributes([
//                            
                    ]);


                    echo $this->form()->openTag($form);
                    ?>
                    <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                    <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('region')); ?>
                                <div class="required-field-block">
                                    <?= $this->formElement($form->get('region')); ?>
                                    <?= $this->formElementErrors($form->get('region')); ?>
                                    <div class="required-icon">
                                        <div class="text">*</div>
                                    </div> 
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('district_name')); ?>
                                <div class="required-field-block">
                                    <?= $this->formElement($form->get('district_name')); ?>
                                    <?= $this->formElementErrors($form->get('district_name')); ?>
                                    <div class="required-icon">
                                        <div class="text">*</div>
                                    </div> 
                                </div>
                            </div>
                        </div>


                    <div class="row col-sm-3" style="margin-top: 10px;">
                        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('district', array('action' => 'index')); ?>" >CANCEL</a> 
                    </div>
                    <?php echo $this->form()->closeTag();?>

                </form>
            </div>

                   </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src = "<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type = "text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/district.js'); ?>" type="text/javascript"></script>



