<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl= $acl_container->acl;
$role= $user_session->role;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/fixedHeader.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/responsive.bootstrap.min.css'); ?>"/>

<div class="am-content">

    <div class="panel panel-default">
        <div class="panel-heading"> 

            <div class="row">
                <div class="col-sm-8">
                    <h2>Manage districts</h2>
                </div>
                <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

            </div>
        </div>


        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <div>

                    <form action="<?php $this->url('district', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        $form->get('district_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Name of District',
                            'autocomplete' => 'off',
                            'id' => 'District Name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);
                        $region = [];
                        foreach ($regions as $r) {
                            $region[$r['id']] = $r['region_name'];
                        }
                        
                        $form->get('region')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Region',
                            'options' => $region,
                            'autocomplete' => 'off',
                            'id' => 'Region',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                        <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>

                        <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('region')); ?>
                                <div class="required-field-block">
                                    <?= $this->formElement($form->get('region')); ?>
                                    <?= $this->formElementErrors($form->get('region')); ?>
                                    <div class="required-icon">
                                        <div class="text">*</div>
                                    </div> 
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('district_name')); ?>
                                <div class="required-field-block">
                                    <?= $this->formElement($form->get('district_name')); ?>
                                    <?= $this->formElementErrors($form->get('district_name')); ?>
                                    <div class="required-icon">
                                        <div class="text">*</div>
                                    </div> 
                                </div>
                            </div>
                        </div>



                        <div class="row col-sm-3" style="margin-top: 10px;">
                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                            <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('district', array('action' => 'index')); ?>" >CANCEL</a> 
                        </div>
                        <?php echo $this->form()->closeTag(); ?>

                    </form>
                </div>


                <div style="margin-top:120px;">
                    <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width: 70%;">
                        <thead>
                            <tr>

                                <th>District Name </th>
                                <th> Region </th>
                                <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\District', 'update')) { ; ?>
                                <th>Edit</th> 
                                    <?php } ; ?>
                               <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\District', 'delete')) { ; ?>
                               <th>Delete</th> 
                                   <?php } ; ?>
                            </tr>


                        </thead>
                        <tbody>
                            <?php foreach ($districts as $district): ?>
                                <tr>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($district->district_name); ?></div>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($district->region_name); ?></div>
                                    </td>
                                    <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\District', 'update')) { ; ?>
                              <td>
                                        <div style="width:80px;overflow:auto;"><a href="<?php echo $this->url('district', array('action' => 'edit', 'id' => base64_encode($district->id))); ?>"> <span class="glyphicon glyphicon-pencil">Edit</span></div>

                                        </a> 
                                    </td> <?php } ; ?>
                                    <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\District', 'delete')) { ; ?>
                              <td><div style="overflow:auto;">
                                            <a onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($district->district_name); ?> ' + '?')) {
                                                        alert('Canceled!');
                                                        return false;
                                                    };"  href="<?php echo $this->url('district', array('action' => 'delete', 'id' => base64_encode($district->id))); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                        </div>
                                    </td>
                                    <?php } ; ?>
                                </tr>
                            <?php endforeach; ?>               
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="<?php echo $this->basePath('assets/js/personnel_certification/district.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/jquery-3.1.0.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.bootstrap.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.fixedHeader.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.responsive.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/responsive.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/district.js'); ?>" type="text/javascript"></script>

    <script type="text/javascript" language="javascript" >
                                            $(document).ready(function () {

                                                var table = $('#example').DataTable({
                                                    "aProcessing": true,
                                                    "aServerSide": true,
                                                    responsive: true
                                                });

                                                new $.fn.dataTable.FixedHeader(table);

                                            });


    </script>

