<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl = $acl_container->acl;
$role = $user_session->role
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/jquery-ui.css'); ?>"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<?php
$title = 'Add a new personnel';
$this->headTitle($title);
?>


<div class="am-content">
    <div class="panel panel-default">
        <div class="panel-heading">     
            <div class="row">
                <div class="col-sm-8">
                    <h1><?= $this->escapeHtml($title) ?></h1>
                </div>
                <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\Personnel', 'index')) {  ;?>
                    <div class="col-sm-4">
                        <a href="<?php echo $this->url('personnel', array('action' => 'index')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-list "></i>&nbsp;Personnel list</a>

                    </div>
<?php }; ?>
                <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

            </div>


        </div> 

        <div class="panel-body">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <div>

                    <form action="<?php $this->url('personnel', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        $form->get('first_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'First name',
                            'autocomplete' => 'off',
                            'id' => 'First name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('last_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Last name',
                            'autocomplete' => 'off',
                            'id' => 'Last name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('middle_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Middle name',
                            'id' => 'Middle name',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)',
                            'onkeyup' => "myFunction()"
                        ]);
                        $region = [];
                        foreach ($regions as $r) {
                            $region[$r['id']] = $r['region_name'];
                        }
                        $form->get('region')->setAttributes([
                            'class' => 'form-control',
                            'options' => $region,
                            'autocomplete' => 'off',
                            'id' => 'Region',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showDistrict(this.value)'
                        ]);

                        $form->get('district')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'District',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showFacilities(this.value)',
                        ]);

                        $form->get('affiliation')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'Affiliation',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showFacilities(this.value)',
                        ]);


                        $form->get('phone')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Phone',
                            'id' => 'Phone number',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)'
                        ]);
                        $form->get('email')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Email',
                            'autocomplete' => 'off',
                            'id' => 'Email',
                            'onclick' => 'emptyInput(this)']);

                        $form->get('current_jod')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Current job',
                            'id' => 'Current job title',
                            'onclick' => 'emptyInput(this)']);

                        $form->get('time_worked')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Time worked as assesor/auditor',
                            'autocomplete' => 'off',
                            'id' => 'Time worked as assesor/auditor',
                            'onclick' => 'emptyInput(this)']);

                        $form->get('last_training_date')->setAttributes([
                            'class' => 'form-control',
                            'autocomplete' => 'off',
                            'id' => 'date',
                            'onclick' => 'emptyInput(this)'
                        ]);
                        $form->get('type_of_training')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'Type of activity/training',
                            'onclick' => 'emptyInput(this)'
                        ]);
                        $form->get('length_of_training')->setAttributes([
                            'class' => 'form-control',
                            'autocomplete' => 'off',
                            'id' => 'Length of activity/training',
                            'onclick' => 'emptyInput(this)',
                            'placeholder' => 'Length of training/activity'
                        ]);
                        $form->get('training_organization')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'Training organization',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)'
                        ]);

                        $form->get('training_certificate')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Training certificate',
                            'id' => 'Training certificate',
                            'onchange' => 'issued()',
                            'onclick' => 'emptyInput(this)']);

                        $form->get('date_certificate_issued')->setAttributes([
                            'class' => 'form-control',
                            'autocomplete' => 'off',
                            'id' => 'date2',
                            'onclick' => 'emptyInput(this)',
                        ]);
                        $form->get('Comments')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Comments',
                            'autocomplete' => 'off',
                            'id' => 'Comments',
                            'onclick' => 'emptyInput(this)']);




                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                            <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                        <div class="form-group col-lg-4"> 
                                <?= $this->formLabel($form->get('first_name')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('first_name')); ?>
<?= $this->formElementErrors($form->get('first_name')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-lg-4"> 
                                <?= $this->formLabel($form->get('last_name')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('last_name')); ?>
<?= $this->formElementErrors($form->get('last_name')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-4"> 
                            <?= $this->formLabel($form->get('middle_name')); ?>
                            <?= $this->formElement($form->get('middle_name')); ?>
<?= $this->formElementErrors($form->get('middle_name')); ?>

                        </div>
                </div>

                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('phone')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('phone')); ?>
<?= $this->formElementErrors($form->get('phone')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-lg-4"> 
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
<?= $this->formElementErrors($form->get('email')); ?>

                </div>

                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('region')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('region')); ?>
<?= $this->formElementErrors($form->get('region')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('district')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('district')); ?>
<?= $this->formElementErrors($form->get('district')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('affiliation')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('affiliation')); ?>
<?= $this->formElementErrors($form->get('affiliation')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4">
                    <div class = "input-group" >
                        <div> <?= $this->formLabel($form->get('time_worked')); ?></div>
                        <div>
                            <span class="col-lg-8 row" >
                                <?= $this->formElement($form->get('time_worked')); ?>
<?= $this->formElementErrors($form->get('time_worked')); ?>

                            </span>
                            <span class="required-field-block">
                                <select class="form-control" style="margin-bottom: -28px;width: 100px;" name="select_time" id="Time" onclick = 'emptyInput(this)'> 
                                    <option  value="">--Select--</option>
                                    <option id="Years" value="Years">Year(s)</option>
                                    <option id="Months" value="Months">Month(s)</option>
                                    <option id="Weeks" value="Weeks">Week(s)</option>
                                    <option id="Days" value="Days">Day(s)</option>
                                </select>
                                <div class="required-icon" style="margin-top: 10px;">
                                    <div class="text">*</div>
                                </div>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('current_jod')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('current_jod')); ?>
<?= $this->formElementErrors($form->get('current_jod')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('last_training_date')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('last_training_date')); ?>
<?= $this->formElementErrors($form->get('last_training_date')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>

                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('type_of_training')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('type_of_training')); ?>
<?= $this->formElementErrors($form->get('type_of_training')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4">
                    <div class = "input-group" >
                        <div> <?= $this->formLabel($form->get('length_of_training')); ?></div>
                        <div>
                            <span class="col-lg-8 row" >
                                <?= $this->formElement($form->get('length_of_training')); ?>
<?= $this->formElementErrors($form->get('length_of_training')); ?>

                            </span>
                            <span class="required-field-block">
                                <select class="form-control" style="margin-bottom: -28px;width: 100px;" name="select_time2" id="Time2" onclick = 'emptyInput(this)'> 
                                    <option  value="">--Select--</option>
                                    <option id="Years" value="Years">Year(s)</option>
                                    <option id="Months" value="Months">Month(s)</option>
                                    <option id="Weeks" value="Weeks">Week(s)</option>
                                    <option id="Days" value="Days">Day(s)</option>
                                </select>
                                <div class="required-icon" style="margin-top: 10px;">
                                    <div class="text">*</div>
                                </div>
                            </span>


                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                        <?= $this->formLabel($form->get('training_organization')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('training_organization')); ?>
<?= $this->formElementErrors($form->get('training_organization')); ?>
                        <div class="required-icon">
                            <div class="text">*</div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-lg-4"> 
                    <?= $this->formLabel($form->get('training_certificate')); ?>
                    <?= $this->formElement($form->get('training_certificate')); ?>
<?= $this->formElementErrors($form->get('training_certificate')); ?>
                </div>

                <div class="form-group col-lg-4" id="date_issued"> 
                    <?= $this->formLabel($form->get('date_certificate_issued')); ?>
                    <?= $this->formElement($form->get('date_certificate_issued')); ?>
<?= $this->formElementErrors($form->get('date_certificate_issued')); ?>
                </div>


                <div class="form-group col-lg-4"> 
                    <?= $this->formLabel($form->get('Comments')); ?>
                    <?= $this->formElement($form->get('Comments')); ?>
<?= $this->formElementErrors($form->get('Comments')); ?>
                </div>

                <div class="row col-sm-3" style="margin-top: 30px; margin-left: 5px">
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('personnel', array('action' => 'index')); ?>" >CANCEL</a> 
                </div>
<?php echo $this->form()->closeTag(); ?>

                </form>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('js/personnel.js'); ?>" type="text/javascript"></script>
<script>
                                    function showDistrict(str) {

                                        if (str == "") {
                                            document.getElementById("District").innerHTML = "";
                                            return;
                                        } else {
                                            if (window.XMLHttpRequest) {
                                                // code for IE7+, Firefox, Chrome, Opera, Safari
                                                xmlhttp = new XMLHttpRequest();
                                            } else {
                                                // code for IE6, IE5
                                                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                            }
                                            xmlhttp.onreadystatechange = function () {
                                                if (this.readyState == 4 && this.status == 200) {
                                                    document.getElementById("District").innerHTML = this.responseText;
                                                }
                                            };
                                            xmlhttp.open("GET", "<?php echo $this->url('personnel', array('action' => 'district')); ?>?q=" + str, true);
                                            xmlhttp.send();
                                        }
                                    }


</script>

