
<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl = $acl_container->acl;
$role = $user_session->role
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/jquery-ui.css'); ?>"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<?php
$title = 'Report';
$this->headTitle($title);
?>


<div class="am-content">
    <div class="panel panel-default">
        <div class="panel-heading">     
            <div class="row">
                <div class="col-sm-8">
                    <h1><?= $this->escapeHtml($title) ?></h1>
                </div>
                
            </div>


        </div> 

        <div class="panel-body">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <div>

                    <form action="<?php $this->url('personnel', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        
                        $region = [];
                        foreach ($regions as $r) {
                            $region[$r['id']] = $r['region_name'];
                        }
                        $form->get('region')->setAttributes([
                            'class' => 'form-control',
                            'options' => $region,
                            'autocomplete' => 'off',
                            'id' => 'Region',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showDistrict(this.value)'
                        ]);

                        $form->get('district')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'District',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showFacilities(this.value)',
                        ]);

                        $form->get('affiliation')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'Affiliation',
                            'autocomplete' => 'off',
                            'onclick' => 'emptyInput(this)',
                            'onchange' => 'showFacilities(this.value)',
                        ]);


                       
                        $form->get('current_jod')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Current job',
                            'id' => 'Current job title',
                            'onclick' => 'emptyInput(this)']);

                       
                        $form->get('type_of_training')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'Type of activity/training',
                            'onclick' => 'emptyInput(this)'
                        ]);
                        
                                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                            <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                   <div class="form-group col-lg-6"> 
                        <?= $this->formLabel($form->get('affiliation')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('affiliation')); ?>
<?= $this->formElementErrors($form->get('affiliation')); ?>
                       
                    </div>
                </div>
                
                
                <div class="form-group col-lg-6"> 
                        <?= $this->formLabel($form->get('current_jod')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('current_jod')); ?>
<?= $this->formElementErrors($form->get('current_jod')); ?>
                        
                    </div>
                </div>
                
                <div class="form-group col-lg-6"> 
                        <?= $this->formLabel($form->get('type_of_training')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('type_of_training')); ?>
<?= $this->formElementErrors($form->get('type_of_training')); ?>
                        
                    </div>
                </div>
                        
                        
                <div class="form-group col-lg-6"> 
                        <?= $this->formLabel($form->get('region')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('region')); ?>
<?= $this->formElementErrors($form->get('region')); ?>
                                            </div>
                </div>
                <div class="form-group col-lg-6"> 
                        <?= $this->formLabel($form->get('district')); ?>
                    <div class="required-field-block">
                        <?= $this->formElement($form->get('district')); ?>
<?= $this->formElementErrors($form->get('district')); ?>
                       
                    </div>
                </div>

             
               

                <div class="row col-sm-3" style="margin-top: 30px; margin-left: 5px">
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('personnel', array('action' => 'index')); ?>" >CANCEL</a> 
                </div>
<?php echo $this->form()->closeTag(); ?>

                </form>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('js/personnel.js'); ?>" type="text/javascript"></script>
<script>
                                    function showDistrict(str) {

                                        if (str == "") {
                                            document.getElementById("District").innerHTML = "";
                                            return;
                                        } else {
                                            if (window.XMLHttpRequest) {
                                                // code for IE7+, Firefox, Chrome, Opera, Safari
                                                xmlhttp = new XMLHttpRequest();
                                            } else {
                                                // code for IE6, IE5
                                                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                            }
                                            xmlhttp.onreadystatechange = function () {
                                                if (this.readyState == 4 && this.status == 200) {
                                                    document.getElementById("District").innerHTML = this.responseText;
                                                }
                                            };
                                            xmlhttp.open("GET", "<?php echo $this->url('personnel', array('action' => 'district')); ?>?q=" + str, true);
                                            xmlhttp.send();
                                        }
                                    }


</script>

