<?php

use Zend\Session\Container;

$container = new Container('alert');
?>
<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Personnel Management')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink()
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <!--<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">-->
    </head>
    <body>
        <!--<div class="navbar-fixed-top" style="padding-bottom: 200px;">-->


        <nav class="navbar navbar-fixed-top  cc" role="navigation" id="navbar-top">
            <div class="container" >
                <div class="navbar-header">
<img class="navbar-text" src="<?php echo $this->basePath('img/group.png') ; ?>" id="logo" alt="image"/>
                        
                    <a class="navbar-brand" href="#">
<!--                        <img src="img/group.png" id="logo" alt="image"/>-->
                        &nbsp;&nbsp;&nbsp;<span id="app_name">Personnel management application or M-personnel</span>
                    </a>
                </div>

            </div>
            <nav class="navbar navbar-inverse " role="navigation" >
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div>
                        <!--<img class="navbar-text" src="<?php echo $this->basePath('img/group.png') ; ?>" id="logo" alt="image"/>-->
                        <a class="navbar-brand" href="#">M-PERSONNEL</a>


                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <span class="pull-right">
                            <?php
                            if (!isset($user)) {
                                ;
                                ?>
                                <ul class="btn btn-danger btn-xs" id="btn-login">
                                    <li style="margin-top: 10px;">
                                        <a href="<?php echo $this->url('login'); ?>" style="font-size: 130%; color: white;"><span class="glyphicon glyphicon-user"></span>login</a>
                                    </li>
                                </ul>


                                <?php
                            } else {
                                ;
                                ?>
                                <ul class="btn btn-default btn-xs " id="btn-login">
                                    <li style="margin-top: 10px;">
                                        <a href="<?php echo $this->url('user', array('action' => 'logout')); ?>" > <span class="glyphicon glyphicon-log-out"></span>logout</a>
                                    </li>    
                                <?php }; ?>                   </ul>
                        </span>
                    </div>
                </div><!-- /.container-fluid -->
            </nav>
        </nav>

        <!--</div>-->


        <?php if (isset($user)) {
            ;
            ?>
            <!-- sidebar-->
            <nav class="navbar navbar-inverse  sidebar " role="navigation" style="margin-top: 60px;">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\Personnel', 'index')) {
                                ;
                                ?>

                                <li class="active"><a href="<?php echo $this->url('personnel'); ?>">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
                            <?php }; ?>
                            <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'index')) {
                                ;
                                ?>
                                <li><a href="<?php echo $this->url('user', array('action' => 'index')); ?>">User<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
                            <?php }; ?>
                            <?php if (isset($acl) && $acl->isAllowed($role, 'Application\Controller\Personnel', 'index')) { ; ?>
                               <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Personnel <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a>
                                    <ul class="dropdown-menu forAnimate" role="menu">
                                        <li><a href="<?php echo $this->url('personnel', array('action' => 'index')); ?>">Personnel lists</a></li>
                                        <?php if (isset($acl) && ($acl->isAllowed($role, 'Application\Controller\Personnel', 'report'))) {
; ?>
                                            <li><a href="<?php echo $this->url('personnel', array('action' => 'report')); ?>">report</a></li>
                                <?php }; ?>
        
                                    </ul>
                                </li>
                    <?php }; ?>
    <?php if (isset($acl) && ($acl->isAllowed($role, 'Application\Controller\Region', 'index'))) {
        ;
        ?>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
                                    <ul class="dropdown-menu forAnimate" role="menu">
                                        <li><a href="<?php echo $this->url('region', array('action' => 'index')); ?>">Region</a></li>
                                        <?php if (isset($acl) && ($acl->isAllowed($role, 'Application\Controller\District', 'index'))) {
; ?>
                                            <li><a href="<?php echo $this->url('district', array('action' => 'index')); ?>">District</a></li>
                                <?php }; ?>
        <?php if (isset($acl) && ($acl->isAllowed($role, 'Application\Controller\Role', 'index'))) {
; ?>
                                            <li><a href="<?php echo $this->url('role', array('action' => 'index')); ?>">Role</a></li>
                <?php }; ?>
                                    </ul>
                                </li>
                    <?php }; ?>
                        </ul>
                    </div>
                </div>
            </nav>
<?php }; ?>
        <div class="main">
            <div class="container">
        <?= $this->content ?>
                <hr>

            </div>
        </div>



<?= $this->inlineScript() ?>

        <script type="text/javascript">
            function htmlbodyHeightUpdate() {
                var height3 = $(window).height()
                var height1 = $('.nav').height() + 50
                height2 = $('.main').height()
                if (height2 > height3) {
                    $('html').height(Math.max(height1, height3, height2) + 10);
                    $('body').height(Math.max(height1, height3, height2) + 10);
                } else
                {
                    $('html').height(Math.max(height1, height3, height2));
                    $('body').height(Math.max(height1, height3, height2));
                }

            }
            $(document).ready(function () {
                htmlbodyHeightUpdate()
                $(window).resize(function () {
                    htmlbodyHeightUpdate()
                });
                $(window).scroll(function () {
                    height2 = $('.main').height()
                    htmlbodyHeightUpdate()
                });
            });

            $(document).ready(function () {
<?php
if (isset($container->alertMsg) && $container->alertMsg != "") {
    ?>
                    alert("<?php echo $container->alertMsg; ?>");
    <?php
    $container->alertMsg = "";
    unset($container->alertMsg);
}
?>
            });

            $(function () {
                $('.required-icon').tooltip({
                    placement: 'left',
                    title: 'Required field'
                });
            }
            );
        </script>

    </body>
</html>

