<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl= $acl_container->acl;
$role= $user_session->role;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>

<?php
$title = 'Add a new User';
$this->headTitle($title);
?>


<div class="am-content">
    <div class="panel panel-default">
        <div class="panel-heading">     
            <div class="row">
                <div class="col-sm-8">
                    <h1><?= $this->escapeHtml($title) ?></h1>
                </div>
                <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'index')){?>
                <div class="col-sm-4">
                    <a href="<?php echo $this->url('user', array('action' => 'index')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-list "></i>&nbsp;Users list</a>

                </div>
                <?php } ; ?>
                <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

            </div>


        </div> 

        <div class="panel-body">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <div>

                    <form action="<?php $this->url('user', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        $form->get('first_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'First name',
                            'autocomplete' => 'off',
                            'id' => 'First name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('last_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Last name',
                            'autocomplete' => 'off',
                            'id' => 'Last name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('login')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Login',
                            'autocomplete' => 'off',
                            'id' => 'Login',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('password')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Password',
                            'autocomplete' => 'off',
                            'id' => 'Password',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('confirm-password')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Confirm password',
                            'autocomplete' => 'off',
                            'id' => 'Confirm password',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('email')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Email',
                            'autocomplete' => 'off',
                            'id' => 'Email',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('status')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Status',
                            'autocomplete' => 'off',
                            'id' => 'Status',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);
                        $role = [];
                        foreach ($roles as $r) {
                            $role[$r['id']] = $r['name'];
                        }
                        $form->get('role_id')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Role',
                            'options' => $role,
                            'autocomplete' => 'off',
                            'id' => 'Role',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                        <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('first_name')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('first_name')); ?>
                                <?= $this->formElementErrors($form->get('first_name')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('last_name')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('last_name')); ?>
                                <?= $this->formElementErrors($form->get('last_name')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('email')); ?>
                            <?= $this->formElement($form->get('email')); ?>
                            <?= $this->formElementErrors($form->get('email')); ?>
                        </div>
                        <div class="form-group col-lg-6"> 

                            <?= $this->formLabel($form->get('login')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('login')); ?>
                                <?= $this->formElementErrors($form->get('login')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>

                        </div>

                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('password')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('password')); ?>
                                <?= $this->formElementErrors($form->get('password')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('confirm-password')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('confirm-password')); ?>
                                <?= $this->formElementErrors($form->get('confirm-password')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>


                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('status')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('status')); ?>
                                <?= $this->formElementErrors($form->get('status')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-lg-6" style="border-radius: 0px;"> 
                            <?= $this->formLabel($form->get('role_id')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('role_id')) ?>
                                <?= $this->formElementErrors($form->get('role_id')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="row col-sm-3" style="margin-top: 30px; margin-left: 5px">
                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                            <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('user', array('action' => 'index')); ?>" >CANCEL</a> 
                        </div>
                        <?php echo $this->form()->closeTag(); ?>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('js/user.js'); ?>" type="text/javascript"></script>
