<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl= $acl_container->acl;
$role=$user_session->role;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/fixedHeader.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/responsive.bootstrap.min.css'); ?>"/>

    <?php
$title = 'Users list';
$this->headTitle($title);
?>

<div id="panel-container"  >
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-sm-8">
                    <h1><?= $this->escapeHtml($title) ?></h1>
                </div>
                <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'add')){?>
                
                <div class="col-sm-4">
                    <a href="<?php echo $this->url('user', array('action' => 'add')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-plus "></i>&nbsp;Add User</a>

                </div>
                <?php } ; ?>
            </div>

        </div>
        <div class="panel-body">
            <table id="example" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Role</th>
                        <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'update')){?>
                                        <th>Edit</th>
                        <?php } ; ?>
                        <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'delete')){?>
                
                                        <th>Delete</th>
                        <?php } ; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($user->first_name) ?></td>
                            <td><?= $this->escapeHtml($user->last_name) ?></td>
                            <td><?= $this->escapeHtml($user->email) ?></td>
                            <td><?= $this->escapeHtml($user->status) ?></td>
                            <td><?= $this->escapeHtml($user->name) ?></td>
                           <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'update')){?>
                
                            <td><a href="<?= $this->url('user', ['action' => 'update', 'id' => base64_encode($user->id)]) ?>">Edit</a></td>
                           <?php } ; ?>
                            <?php if( isset($acl) && $acl->isAllowed($role, 'Application\Controller\User', 'delete')){?>
                
                            <td><a onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($user->first_name.' '.$user->last_name); ?> ' + '?')) {
                                                        alert('Canceled!');
                                                        return false;
                                                    };" href="<?= $this->url('user', ['action' => 'delete', 'id' => base64_encode($user->id)]) ?>">Delete</a></td>
                            <?php } ; ?>
                        </tr>
                    <?php endforeach; ?>
                <tbody>
            </table>

        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath('js/jquery-3.1.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.fixedHeader.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/responsive.bootstrap.min.js'); ?>"></script>

<script type="text/javascript" language="javascript" >
    $(document).ready(function () {
        
         var table = $('#example').DataTable( {
             "aProcessing": true,
            "aServerSide": true,
        responsive: true
    } );
 
    new $.fn.dataTable.FixedHeader( table );

           });


</script>
