<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl = $acl_container->acl;
$role_code = $user_session->role
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<style>
    /* The container */
    .container_btn_radio {
        display: inline-block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 22px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    /* Hide the browser's default radio button */
    .container_btn_radio input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
    }

    /* Create a custom radio button */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 25px;
        width: 25px;
        background-color: #eee;
        border-radius: 50%;
    }

    /* On mouse-over, add a grey background color */
    .container_btn_radio:hover input ~ .checkmark {
        background-color: #ccc;
    }

    /* When the radio button is checked, add a blue background */
    .container_btn_radio input:checked ~ .checkmark {
        background-color: #2196F3;
    }

    /* Create the indicator (the dot/circle - hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the indicator (dot/circle) when checked */
    .container_btn_radio input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the indicator (dot/circle) */
    .container_btn_radio .checkmark:after {
        top: 9px;
        left: 9px;
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: white;
    }
</style>
<?php
$title = 'Add a new role';
$this->headTitle($title);
?>
<div class="am-content">
    <div class="panel panel-default">
        <div class="panel-heading">     
            <div class="row">
                <div class="col-sm-8">
                    <h1><?= $this->escapeHtml($title) ?></h1>
                </div>
                <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'add')) {
                    ;
                    ?>
                    <div class="col-sm-4">
                        <a href="<?php echo $this->url('role', array('action' => 'index')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-list "></i>&nbsp;roles list</a>

                    </div>
<?php }; ?>
                <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

            </div>


        </div> 

        <div class="panel-body">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <div>

                    <form action="<?php $this->url('role', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        $form->get('code')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Role code',
                            'autocomplete' => 'off',
                            'id' => 'Role code',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Role name',
                            'autocomplete' => 'off',
                            'id' => 'Role name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('description')->setAttributes([
                            'class' => 'form-control',
                            'autocomplete' => 'off',
                            'id' => 'Description',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('status')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Status',
                            'autocomplete' => 'off',
                            'id' => 'Status',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);

                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                            <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                        <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('code')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('code')); ?>
<?= $this->formElementErrors($form->get('code')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('name')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('name')); ?>
<?= $this->formElementErrors($form->get('name')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-lg-6"> 
                            <?= $this->formLabel($form->get('description')); ?>
                            <?= $this->formElement($form->get('description')); ?>
<?= $this->formElementErrors($form->get('description')); ?>
                        </div>

                        <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('status')); ?>
                            <div class="required-field-block">
                                <?= $this->formElement($form->get('status')); ?>
<?= $this->formElementErrors($form->get('status')); ?>
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                            </div>
                        </div>

                        <div class="row col-sm-3" style="margin-top: 30px; margin-left: 5px">
<?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-danger')); ?>
                            <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('role', array('action' => 'index')); ?>" >CANCEL</a> 
                        </div>
<?php echo $this->form()->closeTag(); ?>

                        <table class="table table-striped table-bordered" cellspacing="0" width="100%" >
<?php foreach ($ressources as $ressource) :; ?>
                                <tr><td> <h4><?php echo $ressource; ?></h4></td>

                                     

    <?php // foreach ($privileges as $privilege) :; ?>



                                        <td> <p> <?php echo $privileges[$ressource]?></p>


                                            <label class="container_btn_radio" style="padding-right: 10px;"><span class="glyphicon glyphicon-ok"></span>
                                                <input type="radio" name="radio">
                                                <span class="checkmark"></span>
                                            </label>
                                            <label class="container_btn_radio"><span class="glyphicon glyphicon-remove"></span>
                                                <input type="radio" name="radio" checked="checked">
                                                <span class="checkmark"></span>
                                            </label></td>

    <?php // endforeach; ?>

                                </tr>





<?php endforeach;
; ?>



                        </table>
                    </form>
                     <pre><?php print_r($privileges) ; ?></pre>
        
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('js/role.js'); ?>" type="text/javascript"></script>

