<?php

use Zend\Session\Container;

$container = new Container('alert');
$acl_container = new Container('acl');
$user_session = new Container('user');
$acl = $acl_container->acl;
$role_code = $user_session->role
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/fixedHeader.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('css/responsive.bootstrap.min.css'); ?>"/>


<div class="am-content">
    <div class="panel panel-default">
        <div class="panel-heading"> 
            <div class="row">
                <div class="col-sm-8">
                    <h2>Manage roles</h2>
                </div>
                <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'index')) { ; ?>
                  <div class="col-sm-4">
                    <a href="<?php echo $this->url('role', array('action' => 'add')); ?>" class="btn btn-primary pull-right" ><i class="glyphicon glyphicon-plus "></i>&nbsp;Add role</a>
                </div>
                <?php } ; ?>
            </div>
        </div>

        <div class="panel-body">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div>
                    <table id="example" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>

                                <th>Role code </th>
                                <th>Role name </th>
                                <th>Description </th>
                                <th>Status </th>
                                <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'update')) { ; ?>
                  <th>Edit</th>
                                <?php } ; ?>
                               <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'delete')) { ; ?>
                   <th>Delete</th>
                               <?php } ; ?>
                            </tr>

                        </thead>
                        <tbody>
                            <?php foreach ($roles as $role): ?>
                                <tr>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($role->code); ?></div></td>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($role->name); ?></div></td>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($role->description); ?></div></td>
                                    <td><div style="width:200px;overflow:auto;"><?php echo $this->escapeHtml($role->status); ?></div></td>

                                  <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'update')) { ; ?>
                    <td>
                                        <div style="width:80px;overflow:auto;"><a href="<?php echo $this->url('role', array('action' => 'update', 'id' => base64_encode($role->id))); ?>"> <span class="glyphicon glyphicon-pencil">Edit</span></div>

                                        </a> 
                                    </td>
                                  <?php } ; ?>
                                   <?php if (isset($acl) && $acl->isAllowed($role_code, 'Application\Controller\Role', 'delete')) { ; ?>
                   <td><div style="overflow:auto;">
                                            <a onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($role->name); ?> ' + '?')) {
                                                            alert('Canceled!');
                                                            return false;
                                                        }
                                                        ;"  href="<?php echo $this->url('role', array('action' => 'delete', 'id' => $role->id)); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                   <?php } ; ?>
                                        </div>
                                    </td>


                                </tr>
                            <?php endforeach; ?>               
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath('js/jquery-3.1.0.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.fixedHeader.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/region.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript" >
                                                $(document).ready(function () {

                                                    var table = $('#example').DataTable({
                                                        "aProcessing": true,
                                                        "aServerSide": true,
                                                        responsive: true
                                                    });

                                                    new $.fn.dataTable.FixedHeader(table);

                                                });

</script>



